name: CustomChat
version: '${version}'
main: org.rexi.customChat.CustomChat
api-version: '1.18'
author: Rexi666
depend: [PlaceholderAPI]
commands:
  customchat:
    description: Main command for CustomChat plugin
    aliases: [cc]
  chatcolor:
    description: Opens the chat color menu
    aliases: [colorchat]
permissions:
  customchat.format.default:
    description: Default format permission
    default: true